/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/agents/': RouteRecordInfo<
      '/agents/',
      '/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/agents/[key]': RouteRecordInfo<
      '/agents/[key]',
      '/agents/:key',
      { key: ParamValue<true> },
      { key: ParamValue<false> },
      | '/agents/[key]/'
      | '/agents/[key]/prompt'
      | '/agents/[key]/skills'
      | '/agents/[key]/tools'
    >,
    '/agents/[key]/': RouteRecordInfo<
      '/agents/[key]/',
      '/agents/:key',
      { key: ParamValue<true> },
      { key: ParamValue<false> },
      | never
    >,
    '/agents/[key]/prompt': RouteRecordInfo<
      '/agents/[key]/prompt',
      '/agents/:key/prompt',
      { key: ParamValue<true> },
      { key: ParamValue<false> },
      | never
    >,
    '/agents/[key]/skills': RouteRecordInfo<
      '/agents/[key]/skills',
      '/agents/:key/skills',
      { key: ParamValue<true> },
      { key: ParamValue<false> },
      | never
    >,
    '/agents/[key]/tools': RouteRecordInfo<
      '/agents/[key]/tools',
      '/agents/:key/tools',
      { key: ParamValue<true> },
      { key: ParamValue<false> },
      | never
    >,
    '/agents/create': RouteRecordInfo<
      '/agents/create',
      '/agents/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mcp': RouteRecordInfo<
      '/mcp',
      '/mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/s/[id]': RouteRecordInfo<
      '/s/[id]',
      '/s/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/agents/index.vue': {
      routes:
        | '/agents/'
      views:
        | never
    }
    'src/pages/agents/[key].vue': {
      routes:
        | '/agents/[key]'
        | '/agents/[key]/'
        | '/agents/[key]/prompt'
        | '/agents/[key]/skills'
        | '/agents/[key]/tools'
      views:
        | 'default'
    }
    'src/pages/agents/[key]/index.vue': {
      routes:
        | '/agents/[key]/'
      views:
        | never
    }
    'src/pages/agents/[key]/prompt.vue': {
      routes:
        | '/agents/[key]/prompt'
      views:
        | never
    }
    'src/pages/agents/[key]/skills.vue': {
      routes:
        | '/agents/[key]/skills'
      views:
        | never
    }
    'src/pages/agents/[key]/tools.vue': {
      routes:
        | '/agents/[key]/tools'
      views:
        | never
    }
    'src/pages/agents/create.vue': {
      routes:
        | '/agents/create'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/mcp.vue': {
      routes:
        | '/mcp'
      views:
        | never
    }
    'src/pages/s/[id].vue': {
      routes:
        | '/s/[id]'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
